-- Check current vehicles table schema
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'wisata_db' 
AND TABLE_NAME = 'vehicles'
ORDER BY ORDINAL_POSITION;
